config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :nodes do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/node.rb
class Node < ApplicationRecord
  has_many :children, class_name: "Node"
  belongs_to :parent, class_name: "Node", optional: true
  accepts_nested_attributes_for :parent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  def index
    @rootnodes = Node.where(parent: nil)
  end
  def show
    @node = Node.find(params[:id])
    @nodes = Node.all
  end

  def new
    @node = Node.new
    @nodes = Node.all
  end
  def edit
    @node = Node.find(params[:id])
    @nodes = Node.all
  end
  def create
    unless params[:node][:parent] == ""
      @parent = Node.find(params[:node][:parent])
      @node = @parent.children.build(title: params[:node][:title], content: params[:node][:content], parent: @parent)
    else
      params[:node][:parent] = nil
      @node = Node.new(params.require(:node).permit(:parent,:title,:content))
    end

    @node.save
    redirect_to @node
  end

  def update
    @node = Node.find(params[:id])
    unless params[:node][:parent] == "" #if user doesnt want to not have parent
      unless params[:id] == params[:node][:parent] # if the user didnt select a child to be its own parent(error handling)
        @parent = Node.find(params[:node][:parent])
        if @node.update(title: params[:node][:title], content: params[:node][:content], parent: @parent)
          @parent.children << @node # assign new parent
          redirect_to @node
        else
          @nodes = Node.all #makes dropdown work in render
          render 'edit'
        end
      else
        @nodes = Node.all #makes dropdown work in render
        render 'edit'
      end
    else # save node without parent
      if @node.update(title: params[:node][:title], content: params[:node][:content], parent: nil)
        redirect_to @node
      else
        @nodes = Node.all # makes dropdown work in render
        render 'edit'
      end
    end
  end

  private
  def node_params

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
  def showNestedChildren(node, level)
    puts node.children.to_yaml
    if node.children.any?
      returnme = "<details class=\"indent\"><summary>#{node.title}</summary>".html_safe
      node.children.each do |nestednode|
        returnme += (showNestedChildren(nestednode, level + 1)).html_safe
      end
      returnme += "</details>".html_safe
    else
      returnme = "<div class=\"indent\">#{node.title}</div>".html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nodes/edit.html.erb
<h1>edit wiki page</h1>
<%= form_with(model: @node, local: true) do |form| %>
  <p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
  </p>

  <p>
  <%= form.label :content %><br>
  <%= form.text_area :content %>
  </p>

  <%= form.collection_select :parent, @nodes, :id, :title, include_blank: true, :selected => @node&.parent&.id %>
  

  <p>
  <%= form.submit %>
  </p>
<% end %>

<% link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1> suh </h1>

<p>
<% @rootnodes.each do |rootnode| %>
  <% if rootnode.children.any? %>
    <details class="indent">
      <summary><%= rootnode.title %></summary>
      <% rootnode.children.each do |node| %>
        <%= showNestedChildren(node, 1) %>
      <% end %>
    </details>
  <% else %>
      <div class="indent"><%= rootnode.title %></div>
  <% end %>
<% end %>
</p>

<details>
  <summary>See More</summary>
  This text will be hidden if your browser supports it.
</details>

app/views/nodes/new.html.erb
<h1>new wiki page</h1>
<%= form_with scope: :node, url: nodes_path, local: true do |form| %>
  <p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
  </p>

  <p>
  <%= form.label :content %><br>
  <%= form.text_area :content %>
  </p>

  <%= form.collection_select :parent, @nodes, :id, :title, include_blank: true %>

  <p>
  <%= form.submit %>
  </p>
<% end %>

app/views/nodes/show.html.erb
<p>
<strong>Title:</strong>
<%= @node.title %>
</p>

<p>
<strong>Content:</strong>
<%= @node.content %>
<% @node.children.each do |child| %>
  <%= child.id %>
<% end %>
</p>